import {
  BUILTIN_FIELD_IDS,
  FieldSpec,
} from '../contracts/field-registry.contract';

export const BUILTIN_FIELD_SPECS: FieldSpec[] = [
  {
    id: BUILTIN_FIELD_IDS.name,
    name: 'Name',
    type: 'text',
    source: 'builtin',
    sectionId: 'S1',
    sortable: true,
    filterable: true,
  },
  {
    id: BUILTIN_FIELD_IDS.grade,
    name: 'Grade',
    type: 'text',
    source: 'builtin',
    sectionId: 'S4',
    sortable: true,
    filterable: true,
    editable: true,
  },
  {
    id: BUILTIN_FIELD_IDS.position,
    name: 'Position',
    type: 'text',
    source: 'builtin',
    sectionId: 'S1',
    sortable: true,
    filterable: true,
    editable: true,
  },
  {
    id: BUILTIN_FIELD_IDS.department,
    name: 'Department',
    type: 'text',
    source: 'builtin',
    sectionId: 'S1',
    sortable: true,
    filterable: true,
  },
  {
    id: BUILTIN_FIELD_IDS.employment_type,
    name: 'Employment type',
    type: 'text',
    source: 'builtin',
    sectionId: 'S4',
    sortable: true,
    filterable: true,
    editable: true,
  },
  {
    id: BUILTIN_FIELD_IDS.years_with_company,
    name: 'Years with company',
    type: 'number',
    source: 'derived',
    sectionId: 'S4',
    sortable: true,
    filterable: true,
  },
  {
    id: BUILTIN_FIELD_IDS.current_leave_dates,
    name: 'Current leave dates',
    type: 'text',
    source: 'derived',
    sectionId: 'S10',
    sortable: false,
    filterable: false,
  },
  {
    id: BUILTIN_FIELD_IDS.project_names,
    name: 'Project names',
    type: 'text',
    source: 'derived',
    sectionId: 'S11',
    sortable: false,
    filterable: false,
  },
];

export {
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  MIN_PAGE,
} from '../contracts/employee-list.constants';
